In [1]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder

In [2]:
housing=pd.read_csv('housing.csv')
housing

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [3]:
coor_matrix = housing.corr(numeric_only=True)

In [4]:
coor_matrix['median_house_value'].sort_values(ascending=False)

median_house_value    1.000000
median_income         0.688075
total_rooms           0.134153
housing_median_age    0.105623
households            0.065843
total_bedrooms        0.049686
population           -0.024650
longitude            -0.045967
latitude             -0.144160
Name: median_house_value, dtype: float64

In [5]:
housing['rooms_per_house'] = housing['total_rooms']/housing['households']

In [6]:
def roun(x):
    return round(x)
housing['rooms_per_house']=housing['rooms_per_house'].apply(roun)

In [7]:
housing.isna().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
rooms_per_house         0
dtype: int64

In [8]:
imputer =SimpleImputer(strategy="median")
housing_num = housing.select_dtypes(include=[np.number])

In [9]:
imputer.fit(housing_num)

SimpleImputer(strategy='median')

In [10]:
housing_num=pd.DataFrame(
    imputer.fit_transform(housing_num),
    columns=housing_num.columns)

In [11]:
housing[housing_num.columns] = housing_num

In [12]:
housing_cat = housing[['ocean_proximity']]
cat_encoder= OneHotEncoder()
housing_cat_enc= cat_encoder.fit_transform(housing_cat)

In [13]:
housing_cat=pd.DataFrame(
    housing_cat_enc.toarray(),
    columns= cat_encoder.get_feature_names_out())

In [14]:
housing = pd.concat([housing,housing_cat],axis=1)

In [15]:
housing=housing.drop('ocean_proximity',axis=1)
housing.columns = housing.columns.str.replace('ocean_proximity_','',regex=False)

In [16]:
housing['bedroms_ratio'] = housing['total_bedrooms']/housing['total_rooms']
housing['people_per_house'] = housing['population']/housing['households']

In [17]:
def roun(x):
    return round(x)
housing['people_per_house']=housing['people_per_house'].apply(roun)

In [18]:
coor_matrix = housing.corr(numeric_only=True)
coor_matrix['median_house_value'].sort_values(ascending=False)

median_house_value    1.000000
median_income         0.688075
<1H OCEAN             0.256617
NEAR BAY              0.160284
rooms_per_house       0.151927
NEAR OCEAN            0.141862
total_rooms           0.134153
housing_median_age    0.105623
households            0.065843
total_bedrooms        0.049457
ISLAND                0.023416
people_per_house     -0.023265
population           -0.024650
longitude            -0.045967
latitude             -0.144160
bedroms_ratio        -0.233303
INLAND               -0.484859
Name: median_house_value, dtype: float64

In [19]:
housing

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,rooms_per_house,<1H OCEAN,INLAND,ISLAND,NEAR BAY,NEAR OCEAN,bedroms_ratio,people_per_house
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,7.0,0.0,0.0,0.0,1.0,0.0,0.146591,3
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,6.0,0.0,0.0,0.0,1.0,0.0,0.155797,2
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,8.0,0.0,0.0,0.0,1.0,0.0,0.129516,3
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,6.0,0.0,0.0,0.0,1.0,0.0,0.184458,3
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,6.0,0.0,0.0,0.0,1.0,0.0,0.172096,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,5.0,0.0,1.0,0.0,0.0,0.0,0.224625,3
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,6.0,0.0,1.0,0.0,0.0,0.0,0.215208,3
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,5.0,0.0,1.0,0.0,0.0,0.0,0.215173,2
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,5.0,0.0,1.0,0.0,0.0,0.0,0.219892,2
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,5.0,0.0,1.0,0.0,0.0,0.0,0.221185,3